# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 932d0e38f30bbb9d611932e7c8336ac5d77b5d73062f7f0692bc7d7de25194a4b2b50bf5b23304d78d62f0c1a8459a0ef9edbf5306b298a5f30ef4871812ae28

test:
  secret_key_base: 3ffc4991cb795b1e2e83d503eab1c5a93cb9d5b0a71698c2d3c8a38b11454363edb7a5321ac81d78392b316bd8497c9c35d5e2c6ab387e5d2e1c4e21bdcf1bbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
